name: Build and Test
on: [push, pull_request]
jobs:
  ubuntu:
    strategy:
      matrix:
          version: ["8.2", "8.3", "8.4", "8.5"]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout pecl-memcache extension
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.version}}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install zlib1g-dev memcached
          sudo systemctl stop memcached
      - name: Start memcached daemons
        run: |
          mkdir -p /var/run/memcached
          sudo chmod a+w /var/run/memcached
          /usr/bin/memcached -m 64 -s /var/run/memcached/memcached.sock -d
          /usr/bin/memcached -m 64 -U 11211 -l 127.0.0.1 -p 11211 -d
          /usr/bin/memcached -m 64 -U 11212 -l 127.0.0.1 -p 11212 -d
      - name: phpize
        run: phpize
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: test
        run: |
          MEMCACHE_PROTOCOL=ascii make test TESTS="--show-diff"
          MEMCACHE_PROTOCOL=binary make test TESTS="--show-diff"
